from fpdf import FPDF
import pandas as pd
from datetime import datetime
import io


class NexusRetailReport(FPDF):

    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 80, 30)
        self.cell(0, 10, "NEXUS Retail | Sales & Revenue Intelligence Report",
                  ln=True, align="C")
        self.set_draw_color(30, 80, 30)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10,
                  f"Generated by NEXUS Retail | Page {self.page_no()} | "
                  f"{datetime.now().strftime('%B %d, %Y')}",
                  align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 80, 30)
        self.set_fill_color(235, 245, 235)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.ln(2)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, str(text))
        self.ln(2)

    def kpi_row(self, label, value):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(30, 80, 30)
        self.cell(80, 7, label, border=0)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 7, str(value), border=0, ln=True)


def generate_pdf_report(df, col_map, analytics_summary,
                        executive_brief, trust_report, alerts):
    """
    Generate a complete PDF report of the NEXUS Retail analysis.
    Returns bytes that can be downloaded from Streamlit.
    """
    pdf = NexusRetailReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    today = datetime.now().strftime("%B %d, %Y")

    # ── Cover ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 80, 30)
    pdf.ln(5)
    pdf.cell(0, 12, "Retail Sales & Revenue Intelligence Report",
             ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6,
             f"Generated: {today} | Dataset: {len(df):,} orders | "
             f"Powered by NEXUS Retail",
             ln=True, align="C")
    pdf.ln(6)

    # ── Data Trust Report ──────────────────────────────────────────────
    pdf.section_title("1. DATA QUALITY ASSESSMENT")
    if trust_report:
        score = trust_report.get("trust_score", "N/A")
        label = ("Excellent" if score >= 90 else
                 "Good" if score >= 75 else
                 "Fair" if score >= 60 else "Poor")
        pdf.kpi_row("Data Trust Score:", f"{score}/100 ({label})")
        pdf.kpi_row("Original Rows:", str(trust_report.get("original_rows", "N/A")))
        pdf.kpi_row("Rows After Cleaning:", str(trust_report.get("final_rows", "N/A")))
        pdf.kpi_row("Duplicate Rows Removed:", str(trust_report.get("rows_removed", 0)))
        pdf.kpi_row("Issues Found:", str(len(trust_report.get("issues_found", []))))
        if trust_report.get("issues_found"):
            pdf.body_text("Issues found:\n" + "\n".join(
                f"• {i}" for i in trust_report["issues_found"]
            ))
        if trust_report.get("imputation_log"):
            pdf.body_text("Imputation decisions:\n" + "\n".join(
                f"• {i}" for i in trust_report["imputation_log"]
            ))
    pdf.ln(3)

    # ── Proactive Alerts ───────────────────────────────────────────────
    if alerts:
        pdf.section_title("2. PROACTIVE INTELLIGENCE ALERTS")
        for alert in alerts:
            level = alert.get("level", "info").upper()
            color = (200, 50, 50) if level == "CRITICAL" else (180, 100, 20)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*color)
            pdf.cell(0, 7,
                     f"{alert.get('icon', '')} [{level}] {alert.get('title', '')}",
                     ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, alert.get("message", ""))
            pdf.ln(2)
    pdf.ln(3)

    # ── Executive Brief ────────────────────────────────────────────────
    pdf.section_title("3. AI-GENERATED EXECUTIVE BRIEF")
    if executive_brief:
        pdf.body_text(executive_brief)
    else:
        pdf.body_text("Generate the Executive Brief from the app to include it here.")
    pdf.ln(3)

    # ── Analytics Summary ──────────────────────────────────────────────
    pdf.section_title("4. KEY ANALYTICS FINDINGS")
    if analytics_summary:
        pdf.body_text(analytics_summary)
    pdf.ln(3)

    # ── Footer note ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5,
        "This report was generated by NEXUS Retail, an AI-powered retail "
        "intelligence system. All insights are derived from the uploaded dataset. "
        "Recommendations should be reviewed by qualified business analysts before implementation.")

    return bytes(pdf.output())