from fpdf import FPDF
import pandas as pd
from datetime import datetime
import re

# ── Font paths (DejaVu supports Unicode incl. ₦) ──────────────────────────────
_FONT_DIR = "/usr/share/fonts/truetype/dejavu/"
_FONT_REG  = _FONT_DIR + "DejaVuSans.ttf"
_FONT_BOLD = _FONT_DIR + "DejaVuSans-Bold.ttf"
_FONT_ITAL = _FONT_DIR + "DejaVuSans-Oblique.ttf"

# Accent colour (deep green)
_GREEN = (30, 80, 30)
_LIGHT_GREEN_FILL = (235, 245, 235)


def _sanitize(text: str) -> str:
    """
    Replace characters that cause issues even with Unicode fonts,
    and normalise common smart-quotes / dashes.
    """
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u20a6": "NGN ",   # ₦  → NGN  (keep it readable without the glyph)
        "\u2019": "'",      # right single quote
        "\u2018": "'",      # left single quote
        "\u201c": '"',      # left double quote
        "\u201d": '"',      # right double quote
        "\u2013": "-",      # en dash
        "\u2014": "--",     # em dash
        "\u2022": "-",      # bullet •
        "\u00b7": "·",      # middle dot (already Latin-1, keep)
        "\u2026": "...",    # ellipsis
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Strip any remaining non-Latin-1 characters that DejaVu might miss
    # (rare, but safe fallback)
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text


class NexusRetailReport(FPDF):

    def __init__(self):
        super().__init__()
        # Register DejaVu (Unicode-capable) font family
        self.add_font("DejaVu",       "", _FONT_REG,  uni=True)
        self.add_font("DejaVu", "B",  _FONT_BOLD,     uni=True)
        self.add_font("DejaVu", "I",  _FONT_ITAL,     uni=True)

    def header(self):
        self.set_font("DejaVu", "B", 13)
        self.set_text_color(*_GREEN)
        self.cell(0, 10,
                  "NEXUS Retail | Sales & Revenue Intelligence Report",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_draw_color(*_GREEN)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10,
                  f"Generated by NEXUS Retail  |  Page {self.page_no()}  |  "
                  f"{datetime.now().strftime('%B %d, %Y')}",
                  align="C")

    def section_title(self, title: str):
        self.set_font("DejaVu", "B", 11)
        self.set_text_color(*_GREEN)
        self.set_fill_color(*_LIGHT_GREEN_FILL)
        self.cell(0, 8, f"  {_sanitize(title)}",
                  new_x="LMARGIN", new_y="NEXT", fill=True)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("DejaVu", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, _sanitize(text))
        self.ln(2)

    def kpi_row(self, label: str, value: str):
        self.set_font("DejaVu", "B", 10)
        self.set_text_color(*_GREEN)
        self.cell(80, 7, _sanitize(label), border=0)
        self.set_font("DejaVu", "", 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 7, _sanitize(str(value)), border=0,
                  new_x="LMARGIN", new_y="NEXT")


def generate_pdf_report(df, col_map, analytics_summary,
                        executive_brief, trust_report, alerts):
    """
    Generate a complete PDF report of the NEXUS Retail analysis.
    Returns bytes that can be downloaded from Streamlit.
    """
    pdf = NexusRetailReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    today = datetime.now().strftime("%B %d, %Y")

    # ── Cover ──────────────────────────────────────────────────────────
    pdf.set_font("DejaVu", "B", 18)
    pdf.set_text_color(*_GREEN)
    pdf.ln(5)
    pdf.cell(0, 12, "Retail Sales & Revenue Intelligence Report",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6,
             f"Generated: {today}  |  Dataset: {len(df):,} orders  |  "
             "Powered by NEXUS Retail",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    # ── Data Trust Report ──────────────────────────────────────────────
    pdf.section_title("1. DATA QUALITY ASSESSMENT")
    if trust_report:
        score = trust_report.get("trust_score", "N/A")
        if isinstance(score, (int, float)):
            label = ("Excellent" if score >= 90 else
                     "Good"      if score >= 75 else
                     "Fair"      if score >= 60 else "Poor")
        else:
            label = "N/A"
        pdf.kpi_row("Data Trust Score:",        f"{score}/100 ({label})")
        pdf.kpi_row("Original Rows:",           str(trust_report.get("original_rows", "N/A")))
        pdf.kpi_row("Rows After Cleaning:",     str(trust_report.get("final_rows",    "N/A")))
        pdf.kpi_row("Duplicate Rows Removed:",  str(trust_report.get("rows_removed",  0)))
        pdf.kpi_row("Issues Found:",            str(len(trust_report.get("issues_found", []))))
        if trust_report.get("issues_found"):
            pdf.body_text(
                "Issues found:\n" +
                "\n".join(f"- {i}" for i in trust_report["issues_found"])
            )
        if trust_report.get("imputation_log"):
            pdf.body_text(
                "Imputation decisions:\n" +
                "\n".join(f"- {i}" for i in trust_report["imputation_log"])
            )
    pdf.ln(3)

    # ── Proactive Alerts ───────────────────────────────────────────────
    if alerts:
        pdf.section_title("2. PROACTIVE INTELLIGENCE ALERTS")
        for alert in alerts:
            level = alert.get("level", "info").upper()
            color = (200, 50, 50) if level == "CRITICAL" else (180, 100, 20)
            pdf.set_font("DejaVu", "B", 10)
            pdf.set_text_color(*color)
            # Strip emoji from icon — fpdf2 may still choke on some emoji
            icon = re.sub(r'[^\x00-\x7F]', '', alert.get("icon", ""))
            title = _sanitize(alert.get("title", ""))
            pdf.cell(0, 7, f"{icon} [{level}] {title}",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("DejaVu", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, _sanitize(alert.get("message", "")))
            pdf.ln(2)
    pdf.ln(3)

    # ── Executive Brief ────────────────────────────────────────────────
    pdf.section_title("3. AI-GENERATED EXECUTIVE BRIEF")
    if executive_brief:
        pdf.body_text(executive_brief)
    else:
        pdf.body_text(
            "Generate the Executive Brief from the app to include it here."
        )
    pdf.ln(3)

    # ── Analytics Summary ──────────────────────────────────────────────
    pdf.section_title("4. KEY ANALYTICS FINDINGS")
    if analytics_summary:
        pdf.body_text(analytics_summary)
    pdf.ln(3)

    # ── Footer note ────────────────────────────────────────────────────
    pdf.set_font("DejaVu", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5, _sanitize(
        "This report was generated by NEXUS Retail, an AI-powered retail "
        "intelligence system. All insights are derived from the uploaded dataset. "
        "Recommendations should be reviewed by qualified business analysts "
        "before implementation."
    ))

    return bytes(pdf.output())