"""
utils/report.py — PDF generation via reportlab.
Fixed: section markers styled as headers, proper bullet/numbered lists.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, ListFlowable, ListItem,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io, re
from datetime import datetime

_GREEN       = colors.HexColor("#1E501E")
_LIGHT_GREEN = colors.HexColor("#EBF5EB")
_GREY_TEXT   = colors.HexColor("#323232")
_GREY_LIGHT  = colors.HexColor("#787878")
_RED         = colors.HexColor("#C83232")
_ORANGE      = colors.HexColor("#B46414")
_PAGE_W, _PAGE_H = A4


def _sanitize(text: str) -> str:
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u20a6": "NGN ", "\u2019": "'", "\u2018": "'",
        "\u201c": '"',    "\u201d": '"', "\u2013": "-",
        "\u2014": "--",   "\u2022": "-", "\u2026": "...",
        "\u00b7": "-",
    }
    for ch, rep in replacements.items():
        text = text.replace(ch, rep)
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text


def _styles():
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "cover_title", parent=base["Title"],
            fontSize=20, textColor=_GREEN, spaceAfter=6, alignment=TA_CENTER),
        "cover_sub": ParagraphStyle(
            "cover_sub", parent=base["Normal"],
            fontSize=10, textColor=_GREY_LIGHT, spaceAfter=4, alignment=TA_CENTER),
        "section_main": ParagraphStyle(
            "section_main", parent=base["Heading2"],
            fontSize=12, textColor=_GREEN, spaceBefore=14, spaceAfter=4),
        "section_sub": ParagraphStyle(
            "section_sub", parent=base["Heading3"],
            fontSize=11, textColor=_GREEN, spaceBefore=10, spaceAfter=3),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=10, textColor=_GREY_TEXT, leading=15, spaceAfter=6),
        "bullet": ParagraphStyle(
            "bullet", parent=base["Normal"],
            fontSize=10, textColor=_GREY_TEXT, leading=15,
            leftIndent=16, spaceAfter=5),
        "kpi_label": ParagraphStyle(
            "kpi_label", parent=base["Normal"],
            fontSize=10, textColor=_GREEN, fontName="Helvetica-Bold"),
        "kpi_value": ParagraphStyle(
            "kpi_value", parent=base["Normal"],
            fontSize=10, textColor=_GREY_TEXT),
        "alert_crit": ParagraphStyle(
            "alert_crit", parent=base["Normal"],
            fontSize=10, textColor=_RED, fontName="Helvetica-Bold", spaceAfter=2),
        "alert_warn": ParagraphStyle(
            "alert_warn", parent=base["Normal"],
            fontSize=10, textColor=_ORANGE, fontName="Helvetica-Bold", spaceAfter=2),
        "alert_body": ParagraphStyle(
            "alert_body", parent=base["Normal"],
            fontSize=9, textColor=_GREY_TEXT, leading=13, spaceAfter=8),
        "footer_note": ParagraphStyle(
            "footer_note", parent=base["Normal"],
            fontSize=8, textColor=_GREY_LIGHT, leading=12, spaceBefore=10),
    }


def _section_block(title: str, S: dict):
    data = [[Paragraph(_sanitize(title), S["section_main"])]]
    tbl = Table(data, colWidths=[_PAGE_W - 4*cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), _LIGHT_GREEN),
        ("LEFTPADDING",   (0,0), (-1,-1), 8),
        ("RIGHTPADDING",  (0,0), (-1,-1), 8),
        ("TOPPADDING",    (0,0), (-1,-1), 4),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
        ("LINEBELOW",     (0,0), (-1,-1), 1, _GREEN),
    ]))
    return tbl


def _kpi_table(rows, S):
    data = [
        [Paragraph(_sanitize(lbl), S["kpi_label"]),
         Paragraph(_sanitize(str(val)), S["kpi_value"])]
        for lbl, val in rows
    ]
    tbl = Table(data, colWidths=[7*cm, _PAGE_W - 4*cm - 7*cm])
    tbl.setStyle(TableStyle([
        ("VALIGN",        (0,0), (-1,-1), "TOP"),
        ("ROWBACKGROUNDS",(0,0), (-1,-1), [colors.white, colors.HexColor("#F5FAF5")]),
        ("LEFTPADDING",   (0,0), (-1,-1), 4),
        ("RIGHTPADDING",  (0,0), (-1,-1), 4),
        ("TOPPADDING",    (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
    ]))
    return tbl


def _on_page(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setStrokeColor(_GREEN)
    canvas.setLineWidth(1)
    canvas.line(2*cm, h - 1.8*cm, w - 2*cm, h - 1.8*cm)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(_GREEN)
    canvas.drawString(2*cm, h - 1.5*cm, "NEXUS Retail | Revenue Intelligence Report")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(_GREY_LIGHT)
    canvas.drawCentredString(
        w / 2, 1.2*cm,
        f"Generated by NEXUS Retail  |  Page {doc.page}  |  "
        f"{datetime.now().strftime('%B %d, %Y')}",
    )
    canvas.restoreState()


# Section marker pattern: == SOME TITLE ==
_MARKER_RE = re.compile(r'^==\s*(.+?)\s*==$')
# Numbered list item: "1. text" or "1) text"
_NUM_RE    = re.compile(r'^\d+[.)]\s+(.*)')
# Bullet: "- text" or "• text"
_BUL_RE    = re.compile(r'^[-•*]\s+(.*)')


def _brief_to_story(brief_text: str, S: dict) -> list:
    """
    Parse the AI executive brief into reportlab flowables.
    Handles == SECTION == markers, numbered lists, bullet lists, and paragraphs.
    """
    story = []
    lines = brief_text.strip().splitlines()

    # Group consecutive list items together
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            story.append(Spacer(1, 4))
            i += 1
            continue

        # Section marker → green sub-heading
        m = _MARKER_RE.match(line)
        if m:
            heading = m.group(1).title()
            story.append(Spacer(1, 6))
            story.append(Paragraph(_sanitize(heading), S["section_sub"]))
            story.append(HRFlowable(
                width="100%", thickness=0.5, color=_GREEN, spaceAfter=3))
            i += 1
            continue

        # Collect consecutive numbered items into one ListFlowable
        if _NUM_RE.match(line):
            items = []
            while i < len(lines) and _NUM_RE.match(lines[i].strip()):
                content = _NUM_RE.match(lines[i].strip()).group(1)
                items.append(ListItem(
                    Paragraph(_sanitize(content), S["body"]),
                    leftIndent=20, value="circle",
                ))
                i += 1
            story.append(ListFlowable(
                items, bulletType="bullet",
                leftIndent=10, spaceAfter=4,
            ))
            continue

        # Collect consecutive bullet items
        if _BUL_RE.match(line):
            items = []
            while i < len(lines) and _BUL_RE.match(lines[i].strip()):
                content = _BUL_RE.match(lines[i].strip()).group(1)
                items.append(ListItem(
                    Paragraph(_sanitize(content), S["body"]),
                    leftIndent=20,
                ))
                i += 1
            story.append(ListFlowable(
                items, bulletType="bullet",
                leftIndent=10, spaceAfter=4,
            ))
            continue

        # Regular paragraph
        story.append(Paragraph(_sanitize(line), S["body"]))
        i += 1

    return story


def generate_pdf_report(df, col_map, analytics_summary,
                        executive_brief, trust_report, alerts):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2.5*cm, bottomMargin=2*cm,
    )
    S = _styles()
    story = []
    today = datetime.now().strftime("%B %d, %Y")

    # ── Cover ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph(
        "Retail Sales & Revenue Intelligence Report", S["cover_title"]))
    story.append(Paragraph(
        f"Generated: {today}  |  Dataset: {len(df):,} orders  |  Powered by NEXUS Retail",
        S["cover_sub"]))
    story.append(HRFlowable(
        width="100%", thickness=1, color=_GREEN, spaceAfter=16))

    # ── 1. Data Quality ────────────────────────────────────────────────
    story.append(_section_block("1. DATA QUALITY ASSESSMENT", S))
    story.append(Spacer(1, 4))
    if trust_report:
        score = trust_report.get("trust_score", "N/A")
        label = ("N/A" if not isinstance(score, (int, float)) else
                 "Excellent" if score >= 90 else "Good" if score >= 75
                 else "Fair" if score >= 60 else "Poor")
        story.append(_kpi_table([
            ("Data Trust Score:",      f"{score}/100 ({label})"),
            ("Original Rows:",         str(trust_report.get("original_rows", "N/A"))),
            ("Rows After Cleaning:",   str(trust_report.get("final_rows",    "N/A"))),
            ("Duplicates Removed:",    str(trust_report.get("rows_removed",  0))),
            ("Issues Found:",          str(len(trust_report.get("issues_found", [])))),
        ], S))
        if trust_report.get("issues_found"):
            items = [ListItem(Paragraph(_sanitize(x), S["body"]), leftIndent=20)
                     for x in trust_report["issues_found"]]
            story.append(Paragraph("Issues found:", S["kpi_label"]))
            story.append(ListFlowable(items, bulletType="bullet", leftIndent=10))
        if trust_report.get("imputation_log"):
            items = [ListItem(Paragraph(_sanitize(x), S["body"]), leftIndent=20)
                     for x in trust_report["imputation_log"]]
            story.append(Paragraph("Imputation decisions:", S["kpi_label"]))
            story.append(ListFlowable(items, bulletType="bullet", leftIndent=10))
    story.append(Spacer(1, 8))

    # ── 2. Intelligence Alerts ─────────────────────────────────────────
    if alerts:
        story.append(_section_block("2. PROACTIVE INTELLIGENCE ALERTS", S))
        story.append(Spacer(1, 4))
        for alert in alerts:
            level   = alert.get("level", "info").upper()
            a_style = S["alert_crit"] if level == "CRITICAL" else S["alert_warn"]
            title   = _sanitize(alert.get("title", ""))
            msg     = _sanitize(alert.get("message", ""))
            story.append(KeepTogether([
                Paragraph(f"[{level}] {title}", a_style),
                Paragraph(msg, S["alert_body"]),
            ]))
        story.append(Spacer(1, 8))

    # ── 3. Executive Brief ─────────────────────────────────────────────
    story.append(_section_block("3. AI-GENERATED EXECUTIVE BRIEF", S))
    story.append(Spacer(1, 4))
    brief_text = executive_brief or \
        "Generate the Executive Brief from the app to include it here."
    story.extend(_brief_to_story(brief_text, S))
    story.append(Spacer(1, 8))

    # ── 4. Analytics Summary ───────────────────────────────────────────
    story.append(_section_block("4. KEY ANALYTICS FINDINGS", S))
    story.append(Spacer(1, 4))
    if analytics_summary:
        story.append(Paragraph(_sanitize(analytics_summary), S["body"]))
    story.append(Spacer(1, 8))

    # ── Disclaimer ─────────────────────────────────────────────────────
    story.append(HRFlowable(
        width="100%", thickness=0.5, color=_GREY_LIGHT, spaceAfter=4))
    story.append(Paragraph(_sanitize(
        "This report was generated by NEXUS Retail, an AI-powered retail "
        "intelligence system. All insights are derived from the uploaded dataset. "
        "Recommendations should be reviewed by qualified business analysts "
        "before implementation."), S["footer_note"]))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()